version: 2.1

jobs:
  run-python-script:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project
    steps:
      - checkout
      
      # Verify Python is available
      - run:
          name: Check Python version
          command: python --version

      # Install dependencies with error handling
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install telebot pymongo aiohttp python-telegram-bot pyTelegramBotAPI certifi || exit 1

      # More cautious permission setting
      - run:
          name: Set execute permissions
          command: |
            if [ -f "pk.py" ]; then
              chmod +x pk.py
            else
              echo "Error: pk.py not found!"
              exit 1
            fi

      # Run script with error handling
      - run:
          name: Execute Python script
          command: |
            if ! python pk.py; then
              echo "Script failed with exit code $?"
              exit 1
            fi

      # Store specific artifacts
      - store_artifacts:
          path: ~/project
          when: always

workflows:
  scheduled-run:
    triggers:
      - schedule:
          cron: "0 */6 * * *"
          filters:
            branches:
              only: main
    jobs:
      - run-python-script

  manual-run:
    jobs:
      - run-python-script:
          filters:
            branches:
              only: main