version: 2.1

jobs:
  run-python-script:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project
    steps:
      - checkout
      
      # Debug: Show directory structure
      - run:
          name: Verify repository contents
          command: ls -la

      # Python environment setup
      - run:
          name: Setup Python environment
          command: |
            python --version
            pip --version
            python -m pip install --upgrade pip wheel

      # Dependency installation with retry
      - run:
          name: Install dependencies
          command: |
            pip install --retries 3 --timeout 60 \
              telebot \
              pymongo \
              aiohttp \
              python-telegram-bot \
              pyTelegramBotAPI \
              certifi
            pip check  # Verify no dependency conflicts

      # Script preparation
      - run:
          name: Prepare script
          command: |
            if [ ! -f "pk.py" ]; then
              echo "Error: pk.py not found in working directory!"
              ls -la
              exit 1
            fi
            chmod +x pk.py
            file pk.py  # Verify file type

      # Run script with timeout
      - run:
          name: Execute Python script
          command: |
            timeout 300 python pk.py  # 5 minute timeout
            echo "Script exit code: $?"
          no_output_timeout: 10m  # Overall step timeout

      # Store artifacts
      - store_artifacts:
          path: ~/project
          when: always
      - store_test_results:
          path: test-results

workflows:
  scheduled-run:
    triggers:
      - schedule:
          cron: "0 */6 * * *"
          filters:
            branches:
              only: main
    jobs:
      - run-python-script

  manual-run:
    jobs:
      - run-python-script:
          filters:
            branches:
              only: main