version: 2.1

jobs:
  run-python-script:
    docker:
      - image: cimg/python:3.10  # Python-specific image
    working_directory: ~/project
    steps:
      - checkout
      
      # Set up Python environment
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install telebot pymongo aiohttp python-telegram-bot pyTelegramBotAPI certifi

      # Make scripts executable (if needed)
      - run:
          name: Set execute permissions
          command: chmod +x *

      # Run main application
      - run:
          name: Execute Python script
          command: python SOULCRACK.py

      # Store artifacts for debugging
      - store_artifacts:
          path: ~/project
          when: always

workflows:
  scheduled-run:
    triggers:
      - schedule:
          cron: "0 */6 * * *"  # Runs every 6 hours
          filters:
            branches:
              only: main
    jobs:
      - run-python-script

  manual-run:
    jobs:
      - run-python-script:
          filters:
            branches:
              only: main